services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"

  code-execution-service:
    build:
      context: ./code-execution-service
    ports:
      - "8081:8081"
