name: Keep Render Services Alive

on:
  schedule:
    # Run every minute
    - cron: '*/1 * * * *'
  
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  ping-services:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API Gateway
        run: |
          curl -X GET https://codebrewery-api-gateway.onrender.com/ || echo "API Gateway ping sent"
      
      - name: Ping Code Execution Service
        run: |
          curl -X GET https://codebrewery-code-execution-service.onrender.com/ || echo "Code Execution Service ping sent"
          
      - name: Timestamp
        run: echo "Services pinged at $(date)"