name: Keep Render Services Alive

on:
  schedule:
    - cron: '*/2 * * * *'
  push:
    branches:
      - main
      - master

jobs:
  ping-services:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API Gateway
        run: |
          curl -X POST https://codebrewery-api-gateway.onrender.com/execute \
          -H "Content-Type: application/json" \
          -d '{"language":"python","code":"print(\"Keeping service alive\")"}' \
          -v || echo "API Gateway ping sent"
      
      - name: Ping Code Execution Service
        run: |
          curl -X POST https://codebrewery-code-execution-service.onrender.com/execute \
          -H "Content-Type: application/json" \
          -d '{"language":"python","code":"print(\"Keeping service alive\")"}' \
          -v || echo "Code Execution Service ping sent"
          
      - name: Timestamp
        run: echo "Services pinged at $(date)"